# Generated by Django 4.0.3 on 2022-04-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en cours', 'en cours'), ('non livré', 'non livré'), ('livré', 'livré')], max_length=200, null=True)),
                ('date_creation', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
